version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: stra1g-tv-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stra1g_tv_database
    expose: 
      - 5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: stra1g-tv-app
    volumes:
      - .:/home/node
      - /home/node/node_modules
    restart: always
    depends_on:
      - postgres
    ports:
      - 3333:3333
    env_file:
      - .env
    environment:
      NODE_ENV: development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  database: