version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: stra1g-tv-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stra1g_tv_dev
    expose: 
      - 5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: stra1g-tv
    volumes:
      - .:/home/node
      - /home/node/node_modules
    restart: always
    depends_on:
      - postgres
    ports:
      - 3333:3333
      - 8000:8000
      - 1935:1935
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
      NODE_ENV: ${NODE_ENV}
      APP_NAME: ${APP_NAME}
      APP_KEY: ${APP_KEY}

      DB_CONNECTION: ${DB_CONNECTION}

      PG_HOST: postgres
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}
      PG_DB_DEBUG: ${PG_DB_DEBUG}
      PG_SSL: ${PG_SSL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  database: